## Funding config for GPT-Files mirror
custom:
  - https://cash.app/$YaBoiBroke7567
  - https://github.com/Kman182401/ai-trading-system#sponsor-ai-workstation-upgrade
  - mailto:komanderkody18@gmail.com
