[global]
max_file_size_mb = 15
delete_on_repo = true
write_manifest   = false
branch           = "main"

global_excludes = [
  "*.log",
  "*.tmp",
  "*.csv",
  "*.parquet",
  "__pycache__",
  ".git",
  ".mypy_cache",
  ".pytest_cache",
  ".ipynb_checkpoints",
  "ml_env",
  "venv",
  ".venv",
  "node_modules",
  "*.ibgzenc"
]

[[source]]
path = "/home/karson/orders"
dest = "external/orders"
optional = true

[[source]]
path = "/home/karson/tests"
dest = "external/tests"
optional = true

[[source]]
path = "/home/karson/configs"
dest = "external/configs"
optional = true

[[source]]
path = "/home/karson/tools"
dest = "external/tools"
optional = true

[[source]]
path = "/home/karson/workspace/tools"
dest = "external/workspace_tools"
optional = true
