experiment_name: ppo_no_clip
clip_range_vf: null
total_timesteps: 5000
eval_episodes: 100
seeds: [101, 202, 303, 404, 505]
rc_iterations: 1000
target_kl: 0.03
market_data_length: 8000
environment:
  config:
    lookback_window: 64
    use_dict_obs: false
    use_continuous_actions: false
    use_multi_component_reward: true
    use_domain_randomization: true
    max_episode_length: 512
    random_start: true
  use_domain_randomization_train: true
  use_domain_randomization_eval: false
