rl_defaults: &rl_defaults
  train_timesteps: 50000
  n_envs: 1
  seed: 42
  vecnormalize_obs: true
  vecnormalize_reward: true
  policy_kwargs: {}
  algo_kwargs: {}
  use_imitation_warmstart: false
  warmstart_epochs: 3

datasets:
  minute_bars_path: data/minute_bars
  lookback_days: 30

strategies:
  - name: ES_PPO_LSTM
    type: rl_policy
    algo: RecurrentPPO
    policy: MlpLstmPolicy
    rl:
      <<: *rl_defaults
    reward:
      costs_bps: 0.5
      lambda_var: 0.0
      lambda_dd: 0.0
      h_var: 60
      hindsight_H: 120
      hindsight_weight: 0.05
      use_hindsight_in_training: true
  - name: NQ_SAC
    type: rl_policy
    algo: SAC
    policy: MlpPolicy
    rl:
      <<: *rl_defaults
      train_timesteps: 30000
      seed: 123
      algo_kwargs:
        learning_rate: 0.0003
        buffer_size: 1000000
        learning_starts: 100
        batch_size: 256
        tau: 0.005  # Polyak averaging
        gamma: 0.99
        train_freq: 1
        gradient_steps: 1
        ent_coef: auto  # automatic temperature tuning
    reward:
      costs_bps: 0.25
      lambda_var: 0.2
      lambda_dd: 0.05
      h_var: 90
  - name: GC_TD3
    type: rl_policy
    algo: TD3
    policy: MlpPolicy
    rl:
      <<: *rl_defaults
      algo_kwargs:
        learning_rate: 0.0003  # actor & critic lr
        buffer_size: 1000000
        learning_starts: 100
        batch_size: 256
        tau: 0.005
        gamma: 0.99
        train_freq: 1
        gradient_steps: 1
        policy_delay: 2
        target_policy_smoothing:
          noise_std: 0.2
          noise_clip: 0.5
    reward:
      costs_bps: 0.4
      lambda_var: 0.15
      lambda_dd: 0.03
      h_var: 120
  - name: ES_LogReg
    type: supervised
    model: logistic
    params:
      target_col: label
      C: 0.5

cpcv:
  groups: 12
  test_group_size: 2
  embargo_days: 1
  label_lookahead_bars: 1
  folds: 20
  random_state: 7
  rl_fast_smoke: true
  rl_overrides:
    train_timesteps: 5000
  log_dir: artifacts/cpcv_selection

reality_checks:
  n_bootstrap: 1000
  block_len_bars: 78

rl_fast_smoke: true
rl_fast_overrides:
  train_timesteps: 1000

canary:
  fraction: 0.1
  symbols: ["ES"]
